name: Update Posts JSON

on:
  push:
    branches:
      - main  # main 브랜치에 변경이 생길 때 실행

permissions:
  contents: write  # push 권한 설정

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Attempt to build site
        id: jekyll_build
        continue-on-error: true  # 오류가 발생해도 계속 진행
        run: |
          # 빌드를 시도하되 오류가 생기더라도 다음 단계로 진행
          jekyll build 2>&1 | tee build_log.txt || true

      - name: Generate posts.json
        run: |
          # posts.json 파일 생성
          echo "[" > posts.json
          for file in $(ls _posts); do
            echo "\"/_posts/$file\"," >> posts.json
          done
          sed -i '$ s/,$//' posts.json  # 마지막 쉼표 제거
          echo "]" >> posts.json

      - name: Commit posts.json
        continue-on-error: true  # 오류가 발생해도 계속 진행
        run: |
          # GitHub Actions에서 posts.json 파일을 커밋하고 푸시
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts.json
          git commit -m "Update posts.json" || true
          git push || true
